spring:
  application:
    name: shopberry

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=shopberry;encrypt=true;trustServerCertificate=true
    username: sa
    password: Password1!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: app
    database: sql_server

server:
  port: 8090
