spring:
  application:
    name: internet_shop
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=internet_shop;encrypt=true;trustServerCertificate=true
    username: sa
    password: SuperSilneHaslo!2024
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database: sql_server
